/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205728.report5;

public class App {
   

    public static void main(String[] args) {
        /*String str = null;
        try {
            System.out.println(str.length());
        } catch (NullPointerException e) {
            System.out.println("NullPointerException!");
            System.out.println(e.getMessage());
            //TODO: handle exception
        }
        */
        String str = "百二十三";
        int value = Integer.parseInt(str);
    }
}
