/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205728.report5;

public class App {
   

    public static void main(String[] args) {
        String str = null;
        System.out.println(str.length());
    }
}
